<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b59a44c9-2645-4c18-9a5a-95a318efc119</uuid>
  <locale>pt_BR</locale>
  <definition><![CDATA[atribuir à decisão o valor "Desculpe, não temos informações suficientes para criar uma recomendação." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
